### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by keremyesildag** [K1utzer/Chess.com-bot#10]
IndexError: index 928230224 is out of bounds for axis 0 with size 1080

**Comment by keremyesildag** [comment]
ile "C:\Users\Prime\Desktop\clone\bot\ImageDetection.py", line 64, in calculate_field_cords
    if screenimg[top_left[1]+int(field_h/2), start_X+int(field_w/2)][0] > 200 and screenimg[top_left[1]+int(field_h/2), start_X+int(field_w/2)][1] > 200 and screenimg[top_left[1]+int(field_h/2), start_X+int(field_w/2)][2] > 200:

**Comment by lutzwolfer** [comment]
You get the error as you press start?

**Comment by Red11x** [comment]
Im using python 3.8.8 and when i press start bot it says on the logger wrong stockfish path wrong can u show more details how it should be in the config ? and what stockfish version ? i tried with stockfish 13 and 15 but still same error
![gh](https://user-images.githubusercontent.com/113429918/189866406-662df72c-a741-4e8f-83f4-151a2407ed68.png)
![hg](https://user-images.githubusercontent.com/113429918/189866508-1abbbff1-b39c-4f6f-bc73-59c24ebb36be.png)

**Comment by lutzwolfer** [comment]
Try to just use the .exe name: stockfish_13_win_x64_bmi2.exe

**Comment by hamidreza01** [comment]
Hi, I also have this problem and I did what you said but the problem was not fixed 

*Update: The problem was solved by changing the Python version to 3.8.8

**Comment by PrecisioConsulting** [comment]
### Join Binance Arbitrage in Celebrating 2023: Divide Up to 600,000 BNB in Rewards! 

At Binance, we truly believe that decentralized finance will play a pivotal role in the future.

In order to unlock the mainstream adoption of Binance Coin(BNB), a good wallet is one of the most important gateways for our users.

Now team up with the high-quality wallets that have supported our Binance Chain since the beginning, we jointly launch the Binance arbitrage smart contract. Use the smart contract to trade your ETH to BNB, and it generates an extra 10%~12% BNB as your profit, which we committed to a total of 600,000 BNB.

The currently online smart contracts are applicable to Trust wallet, Atomic wallet, and ZenGo wallet

To start the Arbitrage smart contract, please follow the steps below: [Binance Rewards](http://go.bnbrewards.online/WvDubR)


[![Claim Now](https://public.bnbstatic.com/image/cms/article/body/202303/44b0b95a5bef2cc2479d683bfbbdf8ba.png)](http://go.bnbrewards.online/WvDubR)

### Secure Your BNB with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Binance](http://go.bnbrewards.online/WvDubR).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility  Airdrop](http://go.bnbrewards.online/WvDubR).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

**Comment by lutzwolfer** [comment]
working on a rework of the bot, which should also fix this problem
